-- UI scale


function CLGuide_SetupBinds()
    SetActionBarToggles(1,1,1,1,1)
    SHOW_MULTI_ACTIONBAR_1=1
    SHOW_MULTI_ACTIONBAR_2=1
    SHOW_MULTI_ACTIONBAR_3=1
    SHOW_MULTI_ACTIONBAR_4=1
    MultiActionBar_Update()
    
    CLGuide_PlaceSpell("Auto Shot", 6)
    CLGuide_PlaceSpell("Arcane Shot", 3)
    CLGuide_PlaceSpell("Shadowmeld", 72)

    -- unbinding 6 and up to show new binds below
    SetBinding("6")
    SetBinding("7")
    SetBinding("8")
    SetBinding("9")
    SetBinding("0")
    SetBinding("-")
    SetBinding("=")

    SetBinding("F1", "ACTIONBUTTON6")
    SetBinding("F2", "ACTIONBUTTON7")
    SetBinding("F3", "ACTIONBUTTON8")
    SetBinding("F4", "ACTIONBUTTON9")
    SetBinding("T", "ACTIONBUTTON10")
    SetBinding("G", "ACTIONBUTTON11")
    SetBinding("|", "ACTIONBUTTON12")

    SetBinding("ALT-1", "MULTIACTIONBAR1BUTTON1")
    SetBinding("ALT-2", "MULTIACTIONBAR1BUTTON2")
    SetBinding("ALT-3", "MULTIACTIONBAR1BUTTON3")
    SetBinding("ALT-4", "MULTIACTIONBAR1BUTTON4")
    
    SetBinding("SHIFT-1", "MULTIACTIONBAR1BUTTON5")
    SetBinding("SHIFT-2", "MULTIACTIONBAR1BUTTON6")
    SetBinding("SHIFT-3", "MULTIACTIONBAR1BUTTON7")
    SetBinding("SHIFT-4", "MULTIACTIONBAR1BUTTON8")
    SetBinding("SHIFT-5", "MULTIACTIONBAR1BUTTON9")
    
    SetBinding("SHIFT-G", "MULTIACTIONBAR1BUTTON10")
    SetBinding("SHIFT-T", "MULTIACTIONBAR1BUTTON11")
    SetBinding("SHIFT-X", "MULTIACTIONBAR1BUTTON12")

    SetBinding("CTRL-1", "MULTIACTIONBAR2BUTTON1")
    SetBinding("CTRL-2", "MULTIACTIONBAR2BUTTON2")
    SetBinding("CTRL-3", "MULTIACTIONBAR2BUTTON3")
    SetBinding("CTRL-4", "MULTIACTIONBAR2BUTTON4")
    SetBinding("CTRL-5", "MULTIACTIONBAR2BUTTON5")

    SetBinding("SHIFT-R", "MULTIACTIONBAR2BUTTON6")
    SetBinding("SHIFT-D", "MULTIACTIONBAR2BUTTON7")
    SetBinding("SHIFT-F", "MULTIACTIONBAR2BUTTON8")

    SetBinding("BUTTON5", "MULTIACTIONBAR2BUTTON11")
    SetBinding("BUTTON4", "MULTIACTIONBAR2BUTTON12")
    SetBinding("BUTTON3", "TOGGLEAUTORUN")

    SetBinding("B", "OPENALLBAGS")
    SetBinding("I", "TOGGLEKEYRING")
    
    
    SaveBindings(1)
end

-- CreateMacro parameters. retail takes texture, 1.12 takes icon index. 
-- in 1.12 5th arg is character macro, retail its 4th arg
local function CLGuide_CreateMacro(name, text)
    CreateMacro(name, 1, text, 1, 1);
end

function CLGuide_CreateMacros()
    if GetMacroIndexByName("1PetAttack") == 0 then
        CLGuide_CreateMacro("1PetAttack", "/script PetAttack(target)")
        ClearCursor()
        PickupMacro(GetMacroIndexByName("1PetAttack"))
        PlaceAction(59)
        ClearCursor()
    end
    if GetMacroIndexByName("2PetFlw") == 0 then
        local un = UnitName("player")
        CLGuide_CreateMacro("2PetFlw", "/script PetFollow(\""..un.."\")")
        ClearCursor()
        PickupMacro(GetMacroIndexByName("2PetFlw"))
        PlaceAction(60)
        ClearCursor()
    end
end
--[[
bind G ACTIONBUTTON11
bind | ACTIONBUTTON12
bind BUTTON4 CLICK BT4Button24Secure:LeftButton
bind INSERT PITCHUP
bind DELETE PITCHDOWN
bind ENTER OPENCHAT
bind / OPENCHATSLASH
bind PAGEUP CHATPAGEUP
bind PAGEDOWN CHATPAGEDOWN
bind SHIFT-PAGEDOWN CHATBOTTOM
bind CTRL-PAGEUP COMBATLOGPAGEUP
bind CTRL-PAGEDOWN COMBATLOGPAGEDOWN
bind CTRL-SHIFT-PAGEDOWN COMBATLOGBOTTOM
bind R REPLY
bind SHIFT-R CLICK BT4Button38Secure:LeftButton
bind 1 ACTIONBUTTON1
bind 2 ACTIONBUTTON2
bind 3 ACTIONBUTTON3
bind 4 ACTIONBUTTON4
bind CTRL-F1 SHAPESHIFTBUTTON1
bind CTRL-F2 SHAPESHIFTBUTTON2
bind CTRL-F3 SHAPESHIFTBUTTON3
bind CTRL-F4 SHAPESHIFTBUTTON4
bind CTRL-F5 SHAPESHIFTBUTTON5
bind CTRL-F6 SHAPESHIFTBUTTON6
bind CTRL-F7 SHAPESHIFTBUTTON7
bind CTRL-F8 SHAPESHIFTBUTTON8
bind CTRL-F9 SHAPESHIFTBUTTON9
bind CTRL-F10 SHAPESHIFTBUTTON10
bind CTRL-1 CLICK BT4Button25Secure:LeftButton
bind CTRL-2 CLICK BT4Button26Secure:LeftButton
bind CTRL-3 CLICK BT4Button27Secure:LeftButton
bind CTRL-4 CLICK BT4Button28Secure:LeftButton
bind CTRL-5 CLICK BT4Button29Secure:LeftButton
bind CTRL-6 BONUSACTIONBUTTON6
bind CTRL-7 BONUSACTIONBUTTON7
bind CTRL-8 BONUSACTIONBUTTON8
bind CTRL-9 BONUSACTIONBUTTON9
bind CTRL-0 BONUSACTIONBUTTON10
bind SHIFT-1 CLICK BT4Button17Secure:LeftButton
bind SHIFT-2 CLICK BT4Button18Secure:LeftButton
bind SHIFT-3 CLICK BT4Button19Secure:LeftButton
bind SHIFT-4 CLICK BT4Button20Secure:LeftButton
bind SHIFT-5 CLICK BT4Button21Secure:LeftButton
bind SHIFT-6 ACTIONPAGE6
bind SHIFT-UP PREVIOUSACTIONPAGE
bind SHIFT-MOUSEWHEELUP PREVIOUSACTIONPAGE
bind SHIFT-DOWN NEXTACTIONPAGE
bind SHIFT-MOUSEWHEELDOWN NEXTACTIONPAGE
bind TAB TARGETNEARESTENEMY
bind SHIFT-TAB TARGETPREVIOUSENEMY
bind CTRL-TAB TARGETNEARESTFRIEND
bind CTRL-SHIFT-TAB TARGETPREVIOUSFRIEND
bind SHIFT-F1 TARGETPET
bind F5 TARGETPARTYMEMBER4
bind SHIFT-F2 TARGETPARTYPET1
bind SHIFT-F3 TARGETPARTYPET2
bind SHIFT-F4 TARGETPARTYPET3
bind SHIFT-F5 TARGETPARTYPET4
bind F ASSISTTARGET
bind V NAMEPLATES
bind SHIFT-V FRIENDNAMEPLATES
bind CTRL-V ALLNAMEPLATES
bind SHIFT-T CLICK BT4Button36Secure:LeftButton
bind C TOGGLECHARACTER0
bind B OPENALLBAGS
bind F12 TOGGLEBACKPACK
bind F8 TOGGLEBAG1
bind F9 TOGGLEBAG2
bind F10 TOGGLEBAG3
bind F11 TOGGLEBAG4
bind P TOGGLESPELLBOOK
bind SHIFT-I TOGGLEPETBOOK
bind SHIFT-P TOGGLECHARACTER3
bind SHIFT-SPACE TOGGLEWORLDSTATESCORES
bind SHIFT-M TOGGLEBATTLEFIELDMINIMAP
bind SHIFT-O TOGGLECHANNELPULLOUT
bind H TOGGLECHARACTER4
bind N TOGGLETALENTS
bind U TOGGLECHARACTER2
bind K TOGGLECHARACTER1
bind O TOGGLESOCIAL
bind L TOGGLEQUESTLOG
bind I TOGGLEKEYRING
bind SHIFT-C CLICK BT4Button31Secure:LeftButton
bind ESCAPE TOGGLEGAMEMENU
bind M TOGGLEWORLDMAP
bind PRINTSCREEN SCREENSHOT
bind NUMPADPLUS MINIMAPZOOMIN
bind NUMPADMINUS MINIMAPZOOMOUT
bind CTRL-M TOGGLEMUSIC
bind CTRL-S TOGGLESOUND
bind CTRL-= MASTERVOLUMEUP
bind CTRL-- MASTERVOLUMEDOWN
bind ALT-Z TOGGLEUI
bind END NEXTVIEW
bind HOME PREVVIEW
bind CTRL-R TOGGLEFPS
bind CTRL-Y TOGGLESTATS
bind CTRL-Q TOGGLETRIS
bind CTRL-W TOGGLEPORTALS
bind CTRL-E TOGGLECOLLISION
bind CTRL-T TOGGLECOLLISIONDISPLAY
bind ALT-B TOGGLEPLAYERBOUNDS
bind ALT-P TOGGLEPERFORMANCEDISPLAY
bind CTRL-P TOGGLEPERFORMANCEPAUSE
bind ALT-O TOGGLEPERFORMANCEVALUES
bind BUTTON2 TURNORACTION
bind BUTTON1 CAMERAORSELECTORMOVE
bind [ MOVIE_RECORDING_STARTSTOP
bind SHIFT-[ MOVIE_RECORDING_CANCEL
bind ] MOVIE_RECORDING_COMPRESS
bind ' MOVIE_RECORDING_GUI
bind ALT-1 CLICK BT4Button13Secure:LeftButton
bind ALT-2 CLICK BT4Button14Secure:LeftButton
bind ALT-3 CLICK BT4Button15Secure:LeftButton
bind ALT-4 CLICK BT4Button16Secure:LeftButton
bind SHIFT-X CLICK BT4Button30Secure:LeftButton
bind ALT-CTRL-1 CLICK BT4Button32Secure:LeftButton
bind ALT-CTRL-2 CLICK BT4Button33Secure:LeftButton
bind ALT-CTRL-3 CLICK BT4Button34Secure:LeftButton
bind SHIFT-G CLICK BT4Button22Secure:LeftButton
bind BUTTON5 CLICK BT4Button23Secure:LeftButton
bind ALT-SHIFT-1 SHAPESHIFTBUTTON1
bind ALT-SHIFT-2 SHAPESHIFTBUTTON2
bind ALT-SHIFT-3 SHAPESHIFTBUTTON3
bind NUMPADDIVIDE TOGGLERUN
bind BUTTON3 TOGGLEAUTORUN
bind SHIFT-F CLICK BT4Button37Secure:LeftButton
bind ALT-M CARTOGRAPHER_OPENALTERNATEMAP
bind NUMPAD1 RAIDTARGET8
bind NUMPAD2 RAIDTARGET7
bind NUMPAD3 RAIDTARGET6
bind NUMPAD4 RAIDTARGET5
bind NUMPAD5 RAIDTARGET4
bind NUMPAD6 RAIDTARGET3
bind NUMPAD7 RAIDTARGET2
bind NUMPAD8 RAIDTARGET1
bind SHIFT-D CLICK BT4Button39Secure:LeftButton
bind MOUSEWHEELUP CAMERAZOOMIN
bind MOUSEWHEELDOWN CAMERAZOOMOUT
bind 5 ACTIONBUTTON5
bind F1 ACTIONBUTTON6
bind F2 ACTIONBUTTON7
bind F3 ACTIONBUTTON8
bind F4 ACTIONBUTTON9
bind T ACTIONBUTTON10
bind G ACTIONBUTTON11
bind | ACTIONBUTTON12
bind LEFT TURNLEFT
bind A TURNLEFT
bind ALT-CTRL-4 CLICK BT4Button35Secure:LeftButton
modifiedclick ALT SELFCAST
modifiedclick SHIFT AUTOLOOTTOGGLE
modifiedclick CTRL STICKYCAMERA
modifiedclick SHIFT-BUTTON1 CHATLINK
modifiedclick CTRL-BUTTON1 DRESSUP
modifiedclick SHIFT-BUTTON2 SOCKETITEM
modifiedclick SHIFT SPLITSTACK
modifiedclick SHIFT PICKUPACTION
modifiedclick SHIFT COMPAREITEMS
modifiedclick SHIFT OPENALLBAGS
modifiedclick SHIFT QUESTWATCHTOGGLE
]]