-- Author      : G3m7
-- Create Date : 5/4/2019 9:44:47 PM

--[[
SELECT * FROM lh_public.item_template;
select name, SellPrice from lh_public.item_template where Quality = 1 and SellPrice > 1;

SELECT * FROM lh_public.item_template where name like 'Small Barnacle%';
select * from lh_public.item_template where Class=7 and Subclass=0 and SellPrice > 0; -- tradegoods 
select * from lh_public.item_template where Class=15 and Subclass=0 and SellPrice > 0 and Quality > 0; -- junk

select * from lh_public.item_template where Class=7 and Subclass=1 and SellPrice > 0 and Quality > 0; -- tradegoods, parts
select * from lh_public.item_template where Class=7 and Subclass=2 and SellPrice > 0 and Quality > 0; -- tradegoods, explosives
select * from lh_public.item_template where Class=7 and Subclass=3 and SellPrice > 0 and Quality > 0; -- tradegoods, devices
select * from lh_public.item_template where Class=0 and Subclass=0 and SellPrice > 0 and Quality > 0; -- consumable
]]
CLGuide_VendorList = {
"Light Feather"

-- Trade goods, Trade Goods
"Aquamarine",
"Arcane Crystal",
"Arcanite Bar",
"Arcanite Rod",
"Arcanite Skeleton Key",
"Arthas' Tears",
"Azerothian Diamond",
"Bear Meat",
"Big Bear Meat",
"Black Dye",
"Black Lotus",
"Black Lotus",
"Black Pearl",
"Black Vitriol",
"Blank Parchment",
"Bleach",
"Blessed Wizard Oil",
"Blindweed",
"Blood of the Mountain",
"Blood Scythe",
"Blood Shard",
"Bloodvine",
"Blue Dye",
"Blue Sapphire",
"Boar Intestines",
"Boar Ribs",
"Bolt of Linen Cloth",
"Bolt of Mageweave",
"Bolt of Runecloth",
"Bolt of Silk Cloth",
"Bolt of Woolen Cloth",
"Briarthorn",
"Brilliant Mana Oil",
"Brilliant Wizard Oil",
"Broken Blade of Heroes",
"Bronze Bar",
"Bruiseweed",
"Buzzard Wing",
"Charged Scale of Onyxia",
"Chimera Leather",
"Chunk of Boar Meat",
"Citrine",
"Clam Meat",
"Coal",
"Coarse Grinding Stone",
"Coarse Sharpening Stone",
"Coarse Stone",
"Coarse Thread",
"Coarse Weightstone",
"Consecrated Sharpening Stone",
"Copper Bar",
"Copper Ore",
"Copper Rod",
"Core Leather",
"Coyote Meat",
"Crag Boar Rib",
"Crawler Claw",
"Crawler Meat",
"Crimson Lotus",
"Crisp Spider Meat",
"Crocolisk Meat",
"Crystal Vial",
"Cured Heavy Hide",
"Cured Heavy Hide",
"Cured Light Hide",
"Cured Light Hide",
"Cured Medium Hide",
"Cured Medium Hide",
"Cured Rugged Hide",
"Cured Rugged Hide",
"Cured Rugged Hide",
"Cured Thick Hide",
"Cured Thick Hide",
"Dark Iron Bar",
"Dark Iron Ore",
"Dark Rune",
"Deathweed",
"Deeprock Salt",
"Demonic Rune",
"Dense Grinding Stone",
"Dense Sharpening Stone",
"Dense Stone",
"Dense Weightstone",
"Deviate Fish",
"Devilsaur Leather",
"Discolored Worg Heart",
"Dreamfoil",
"Dust of Decay",
"Dust of Deterioration",
"Earthroot",
"Elemental Flux",
"Elemental Sharpening Stone",
"Elementium Bar",
"Elementium Ore",
"Empty Vial",
"Enchanted Leather",
"Enchanted Thorium Bar",
"Engineer's Ink",
"Essence of Agony",
"Essence of Pain",
"Eye of Sulfuras",
"Fadeleaf",
"Felcloth",
"Fine Thread",
"Firebloom",
"Fish Scale",
"Fist-sized Spinneret",
"Flask of Big Mojo",
"Flask of Mojo",
"Flask of Oil",
"Frostsaber Leather",
"Frozen Rune",
"Ghost Dye",
"Ghost Mushroom",
"Giant Clam Meat",
"Giant Egg",
"Gold Bar",
"Gold Ore",
"Golden Pearl",
"Golden Rod",
"Golden Sansam",
"Golden Skeleton Key",
"Goldthorn",
"Gooey Spider Leg",
"Goretusk Liver",
"Goretusk Snout",
"Grave Moss",
"Gray Dye",
"Great Goretusk Snout",
"Green Dye",
"Gromsblood",
"Guardian Stone",
"Heavy Grinding Stone",
"Heavy Hide",
"Heavy Hide",
"Heavy Kodo Meat",
"Heavy Leather",
"Heavy Sharpening Stone",
"Heavy Silken Thread",
"Heavy Stone",
"Heavy Weightstone",
"High Test Eternium Fishing Line",
"Hops",
"Hot Spices",
"Huge Emerald",
"Huge Venom Sac",
"Icecap",
"Imbued Vial",
"Incendicite Ore",
"Iridescent Pearl",
"Iron Bar",
"Iron Counterweight",
"Iron Ore",
"Iron Shield Spike",
"Ironweb Spider Silk",
"Jade",
"Khadgar's Whisker",
"Kingsblood",
"Kodo Meat",
"Large Fang",
"Large Obsidian Shard",
"Large Opal",
"Large Venom Sac",
"Leaded Vial",
"Lean Wolf Flank",
"Lesser Mana Oil",
"Lesser Moonstone",
"Lesser Wizard Oil",
"Lethargy Root",
"Liferoot",
"Light Hide",
"Light Hide",
"Light Leather",
"Linen Cloth",
"Lion Meat",
"Mageroyal",
"Mageweave Cloth",
"Malachite",
"Massive Mojo",
"Meaty Bat Wing",
"Medium Hide",
"Medium Hide",
"Medium Leather",
"Minor Mana Oil",
"Minor Wizard Oil",
"Mithril Bar",
"Mithril Ore",
"Mithril Shield Spike",
"Mithril Spurs",
"Mooncloth",
"Morrowgrain",
"Moss Agate",
"Mountain Silversage",
"Murloc Eye",
"Murloc Fin",
"Mystery Meat",
"Okra",
"Orange Dye",
"Peacebloom",
"Philosopher's Stone",
"Pink Dye",
"Plaguebloom",
"Powerful Mojo",
"Primal Bat Leather",
"Primal Tiger Leather",
"Purple Dye",
"Purple Lotus",
"Raptor Egg",
"Raptor Flesh",
"Raptor Hide",
"Red Dye",
"Red Wolf Meat",
"Refined Deeprock Salt",
"Righteous Orb",
"Rough Grinding Stone",
"Rough Sharpening Stone",
"Rough Stone",
"Rough Weightstone",
"Rugged Hide",
"Rugged Hide",
"Rugged Leather",
"Ruined Leather Scraps",
"Rune Thread",
"Runecloth",
"Runed Arcanite Rod",
"Runed Copper Rod",
"Runed Golden Rod",
"Runed Silver Rod",
"Runed Truesilver Rod",
"Salt",
"Sandworm Meat",
"Scale of Onyxia",
"Scorpid Stinger",
"Shadow Silk",
"Shadowcat Hide",
"Shadowgem",
"Sharp Claw",
"Silk Cloth",
"Silken Thread",
"Silver Bar",
"Silver Ore",
"Silver Rod",
"Silver Skeleton Key",
"Silverleaf",
"Slimy Murloc Scale",
"Small Egg",
"Small Flame Sac",
"Small Lustrous Pearl",
"Small Obsidian Shard",
"Small Spider Leg",
"Small Venom Sac",
"Soft Frenzy Flesh",
"Solid Grinding Stone",
"Solid Sharpening Stone",
"Solid Stone",
"Solid Weightstone",
"Soothing Spices",
"Souldarite",
"Spider Ichor",
"Spider's Silk",
"Stag Meat",
"Star Ruby",
"Steel Bar",
"Steel Weapon Chain",
"Stranglekelp",
"Strider Meat",
"Stringy Vulture Meat",
"Stringy Wolf Meat",
"Strong Flux",
"Sulfuron Ingot",
"Sungrass",
"Swiftthistle",
"Tangy Clam Meat",
"Tender Crab Meat",
"Tender Crocolisk Meat",
"Tender Wolf Meat",
"Thick Hide",
"Thick Hide",
"Thick Leather",
"Thick Murloc Scale",
"Thick Spider's Silk",
"Thick Wolfhide",
"Thin Kodo Leather",
"Thorium Bar",
"Thorium Ore",
"Thorium Shield Spike",
"Thunder Lizard Tail",
"Tiger Meat",
"Tigerseye",
"Tin Bar",
"Tin Ore",
"Tough Condor Meat",
"Truesilver Bar",
"Truesilver Ore",
"Truesilver Rod",
"Truesilver Skeleton Key",
"Turtle Meat",
"Turtle Scale",
"Warbear Leather",
"Weak Flux",
"White Spider Meat",
"Wicked Claw",
"Wild Steelbloom",
"Wildvine",
"Wintersbite",
"Wizard Oil",
"Wool Cloth",
"Yellow Dye",
"Zesty Clam Meat",



-- Trade Goods, Parts
"Rough Blasting Powder",
"Handful of Copper Bolts",
"Copper Tube",
"Copper Modulator",
"Coarse Blasting Powder",
"Bronze Tube",
"Whirring Bronze Gizmo",
"Heavy Blasting Powder",
"Bronze Framework",
"Iron Strut",
"Gyrochronatom",
"Wooden Stock",
"Heavy Stock",
"Silver Contact",
"Gyromatic Micro-Adjustor",
"Solid Blasting Powder",
"Gold Power Core",
"Mithril Tube",
"Unstable Trigger",
"Mithril Casing",
"Dense Blasting Powder",
"Thorium Widget",
"Thorium Tube",
"Delicate Arcanite Converter",
"Truesilver Transformer",


--junk
"Green Hills of Stranglethorn - Page 1",
"Green Hills of Stranglethorn - Page 4",
"Green Hills of Stranglethorn - Page 6",
"Green Hills of Stranglethorn - Page 8",
"Green Hills of Stranglethorn - Page 10",
"Green Hills of Stranglethorn - Page 11",
"Green Hills of Stranglethorn - Page 14",
"Green Hills of Stranglethorn - Page 16",
"Green Hills of Stranglethorn - Page 18",
"Green Hills of Stranglethorn - Page 20",
"Green Hills of Stranglethorn - Page 21",
"Green Hills of Stranglethorn - Page 24",
"Green Hills of Stranglethorn - Page 25",
"Green Hills of Stranglethorn - Page 26",
"Green Hills of Stranglethorn - Page 27",
"Rethban Ore",
"Coarse Gorilla Hair",
"Soft Bushy Tail",
"Long Elegant Feather",
"Ornate Bronze Lockbox",
"Heavy Bronze Lockbox",
"Iron Lockbox",
"Strong Iron Lockbox",
"Steel Lockbox",
"Reinforced Steel Lockbox",
"Vibrant Plume",
"Small Furry Paw",
"Glowing Cat Figurine",
"Lucky Charm",
"Small Barnacled Clam",
"Thick-shelled Clam",
"Mithril Lockbox",
"Thorium Lockbox",
"Eternium Lockbox",
"10 Pound Mud Snapper",
"12 Pound Mud Snapper",
"15 Pound Mud Snapper",
"Message in a Bottle",
"17 Pound Catfish",
"19 Pound Catfish",
"22 Pound Catfish",
"Dented Crate",
"Waterlogged Crate",
"Small Chest",
"Small Locked Chest",
"Sturdy Locked Chest",
"Battered Chest",
"Sealed Crate",
"26 Pound Catfish",
"32 Pound Catfish",
"Practice Lock",
"Box of Supplies",
"Black Whelp Scale",
"Red Whelp Scale",
"Green Whelp Scale",
"Big-mouth Clam",
"Scorpid Scale",
"Worn Dragonscale",
"Wastewander Water Pouch",
"Gadgetzan Water Co. Care Package",
"Cat Carrier (Bombay)",
"Cat Carrier (Cornish Rex)",
"Cat Carrier (Orange Tabby)",
"Cat Carrier (Silver Tabby)",
"Cat Carrier (White Kitten)",
"Cat Carrier (Siamese)",
"Cat Carrier (Black Tabby)",
"Parrot Cage (Green Wing Macaw)",
"Parrot Cage (Hyacinth Macaw)",
"Parrot Cage (Senegal)",
"Parrot Cage (Cockatiel)",
"Rabbit Crate (Snowshoe)",
"Tiny Emerald Whelpling",
"Tiny Crimson Whelpling",
"Great Horned Owl",
"Hawk Owl",
"Troll Tribal Necklace",
"Pirate's Footlocker",
"Security DELTA Data Access Card",
"Sparklematic-Wrapped Box",
"Box of Rations",
"Box of Spells",
"Box of Goodies",
"Black Kingsnake",
"Brown Snake",
"Crimson Snake",
"Cockroach",
"Prairie Dog Whistle",
"Mechanical Chicken",
"Kovic's Trading Satchel",
"Dark Whelpling",
"Un'Goro Soil",
"Ancona Chicken",
"Tree Frog Box",
"Wood Frog Box",
"Chicken Egg",
"Evil Bat Eye",
"Sprite Darter Egg",
"Cenarion Circle Cache",
"Fat Sack of Coins",
"Sack of Gems",
"Small Sack of Coins",
"Worg Carrier",
"Smolderweb Carrier",
"Brilliant Chromatic Scale",
"Chromatic Carapace",
"Deathcharger's Reins",
"Heavy Crate",
"Ironbound Locked Chest",
"40 Pound Grouper",
"47 Pound Grouper",
"53 Pound Grouper",
"59 Pound Grouper",
"68 Pound Grouper",
"42 Pound Redgill",
"45 Pound Redgill",
"49 Pound Redgill",
"34 Pound Redgill",
"37 Pound Redgill",
"52 Pound Redgill",
"15 Pound Salmon",
"18 Pound Salmon",
"22 Pound Salmon",
"25 Pound Salmon",
"29 Pound Salmon",
"32 Pound Salmon",
"7 Pound Lobster",
"9 Pound Lobster",
"12 Pound Lobster",
"15 Pound Lobster",
"19 Pound Lobster",
"21 Pound Lobster",
"22 Pound Lobster",
"70 Pound Mightfish",
"85 Pound Mightfish",
"92 Pound Mightfish",
"103 Pound Mightfish",
"Reinforced Locked Chest",
"Heavy Scorpid Scale",
"Green Dragonscale",
"Red Dragonscale",
"Blue Dragonscale",
"Black Dragonscale",
"Small Brown-wrapped Package",
"A Crazy Grab Bag",
"Shredder Operating Manual - Page 1",
"Shredder Operating Manual - Page 2",
"Shredder Operating Manual - Page 3",
"Shredder Operating Manual - Page 4",
"Shredder Operating Manual - Page 5",
"Shredder Operating Manual - Page 6",
"Shredder Operating Manual - Page 7",
"Shredder Operating Manual - Page 8",
"Shredder Operating Manual - Page 9",
"Shredder Operating Manual - Page 10",
"Shredder Operating Manual - Page 11",
"Shredder Operating Manual - Page 12",
"Light Feather",
"Shiny Fish Scales",
"Fish Oil",
"Blue Sack of Gems",
"Green Sack of Gems",
"Gray Sack of Gems",
"Yellow Sack of Gems",
"Red Sack of Gems",
"A Treatise on Military Ranks",
"Military Ranks of the Horde & Alliance",
"Dark Iron Residue",
"Lard's Special Picnic Basket",
"Ace of Beasts",
"Beasts Deck",
"Two of Beasts",
"Three of Beasts",
"Four of Beasts",
"Five of Beasts",
"Six of Beasts",
"Seven of Beasts",
"Eight of Beasts",
"Warlords Deck",
"Ace of Warlords",
"Two of Warlords",
"Three of Warlords",
"Four of Warlords",
"Five of Warlords",
"Six of Warlords",
"Seven of Warlords",
"Eight of Warlords",
"Elementals Deck",
"Ace of Elementals",
"Two of Elementals",
"Three of Elementals",
"Four of Elementals",
"Five of Elementals",
"Six of Elementals",
"Seven of Elementals",
"Eight of Elementals",
"Ace of Portals",
"Portals Deck",
"Two of Portals",
"Three of Portals",
"Four of Portals",
"Five of Portals",
"Six of Portals",
"Seven of Portals",
"Eight of Portals",
"Lesser Darkmoon Prize",
"Minor Darkmoon Prize",
"Glowing Scorpid Blood",
"Dreamscale",
"Decoded True Believer Clippings",
"Silithid Chitin",
"Light Silithid Carapace",
"Heavy Silithid Carapace",
"Scroll: Create Crest of Beckoning",
"Scroll: Create Crest of Beckoning",
"Scroll: Create Crest of Beckoning",
"Scroll: Create Crest of Beckoning",
"Scroll: Create Signet of Beckoning",
"Scroll: Create Signet of Beckoning",
"Scroll: Create Signet of Beckoning",
"Scroll: Create Signet of Beckoning",
"Scroll: Create Scepter of Beckoning",
"Decoded Twilight Text",
"Scroll: Create Scepter of Beckoning",
"Scroll: Create Scepter of Beckoning",
"Scroll: Create Scepter of Beckoning",
"Decoded Twilight Text",
"Decoded Twilight Text",
"Sack of Spoils",
"Chest of Spoils",
"Bag of Spoils",
"Tightly Sealed Trunk",
"Disgusting Oozeling",
"Followup Logistics Assignment",
"Combat Assignment",
"Tactical Assignment",
"Watertight Trunk",
"Followup Combat Assignment",
"Logistics Assignment",
"Followup Tactical Assignment",
"Iron Bound Trunk",
"Scarab Bag",
"Mithril Bound Trunk",
"Logistics Assignment",
"Followup Logistics Assignment",
"Fel Elemental Rod",
"Ysida's Satchel",
"Mux's Quality Goods",
"Hive'Ashi Dossier",
"Hive'Regal Dossier",
"Hive'Zora Dossier",
"Buccaneer's Uniform",
"The Phylactery of Kel'Thuzad",
"Greater Darkmoon Prize",
"Large Ruffled Feather",
} 